### ISSUE TITLE
请问蓝鲸7.1的版本怎么获取这些变量？

### ISSUE THREAD

**Issue by arsenalpoll** [TencentBlueKing/ci-pushJobFile#6]
7.1版本无法获取以下参数
```shell
source ${CTRL_DIR:-/data/install}/load_env.sh

echo "BK_APP_ID      $BK_CI_APP_CODE"
echo "BK_APP_SECRET  $BK_CI_APP_TOKEN"
echo "ESB_HOST       $BK_PAAS_PRIVATE_URL"
echo "JOB_HOST       $BK_JOB_PUBLIC_URL"
```

**Comment by jsonwan** [comment]
获取BK_APP_ID与BK_APP_SECRET：
查看appCode对应的appSecret
1. 进入bkauth的容器。
2. 运行./bkauth -c config.yaml cli list_access_key -a <appCode1>,<appCode2>

例如：获取appCode为bk_ci对应的appSecret：`kubectl exec deployment/bkauth -n blueking -- sh -c './bkauth -c config.yaml cli list_access_key -a bk_ci'` 

获取ESB_HOST（ESB API地址）：
helm get values -n blueking bk-nodeman | yq e '.bkComponentApiUrl'
获取JOB_HOST（Job首页地址）：
helm get values -n blueking bk-nodeman | yq e '.bkJobUrl'
